Repository kir-dev/tanulo-next, pull requests merged in 2021-04, with the labels that each got.

#616 Fix XSS vulnerability when creating groups
  views/group/new.pug
Labels: bug, high priority, security

#615 Fix user update security vulnerability
  src/components/users/user.service.ts
Labels: bug, high priority, security

#628 Added aria-label for hamburger menu & social links
  views/partials/footer.pug
  views/partials/header.pug
Labels: UI / UX, a11y

#626 Fixed broken MIT link in README.md
  README.md
Labels: documentation

#632 Added SVG alt and aria-label
  views/group/index.pug
  views/group/new.pug
  views/group/show.pug
  views/partials/footer.pug
  views/partials/header.pug
  views/room/roomTemplate.pug
  views/ticket/index.pug
  views/user/show.pug
Labels: UI / UX

#655 Bump jest version
  package.json
  yarn.lock
Labels: dependencies, security
